### ISSUE TITLE
Jump to matching tag?

### ISSUE THREAD

**Issue by Noitidart** [formulahendry/vscode-auto-complete-tag#2]
This bundles two great tag extensions!! Is it possible to get a move cursor to matching tag added in here?

I use this extension with React, so i rarely every work with HTML. It's all JSX. The "Emmet Matching Pair" doesn't work with JSX.

**Comment by formulahendry** [comment]
Thanks @Noitidart  but the feature request is out of scope of these two extensions. 😄

**Comment by Noitidart** [comment]
Agreed. I was hoping you could help by creating a third one :( And possibly if you like, to offer that apart of the bundle.Thanks for considering!

**Comment by KamasamaK** [comment]
The **Auto Rename Tag** extension must already be finding the matching pair, so it would probably be trivial to reuse that logic for a command. That said, this is the extension pack, so it doesn't make sense to have feature requests here.

**Comment by KamasamaK** [comment]
@Noitidart [vincaslt/vscode-highlight-matching-tag](https://github.com/vincaslt/vscode-highlight-matching-tag) just added this.

**Comment by Noitidart** [comment]
Thanks very much @KamasamaK ! Ill try it out!
